---

- hosts: all
  gather_facts: false
  connection: local

  tasks:

   - name: Disable CDP - MGMT Interface
     ios_config:
       parents: Interface GigabitEthernet 6/0
       lines:
         - no cdp enable
